using System.Reflection;
using BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient;

namespace DtoGenerator
{
    /// <summary>
    /// Generates the PHP and Java DTO layers and the golden JSON fixtures from the compiled
    /// .NET client assembly, which stays the single source of truth for the wire format.
    ///
    /// Usage:
    ///   dotnet run --project tools/DtoGenerator -- [--php-out DIR] [--java-out DIR] [--fixtures-out DIR]
    ///
    /// Defaults emit next to the tool: tools/DtoGenerator/out/php, out/java and fixtures/.
    /// Point --php-out/--java-out at the src/Dto respectively dto directories of the port repos
    /// to regenerate them in place.
    /// </summary>
    internal static class Program
    {
        private static int Main(string[] args)
        {
            var toolDir = AppContext.BaseDirectory;
            //When run via "dotnet run" the base directory is bin/Debug/net8.0; the project dir is three up.
            var projectDir = Path.GetFullPath(Path.Combine(toolDir, "..", "..", ".."));
            var phpOut = Path.Combine(projectDir, "out", "php");
            var javaOut = Path.Combine(projectDir, "out", "java");
            var fixturesOut = Path.Combine(projectDir, "fixtures");

            for (var i = 0; i < args.Length - 1; i++)
            {
                switch (args[i])
                {
                    case "--php-out": phpOut = args[++i]; break;
                    case "--java-out": javaOut = args[++i]; break;
                    case "--fixtures-out": fixturesOut = args[++i]; break;
                }
            }

            var assembly = typeof(ScoringProgramRequest).Assembly;
            var version = assembly.GetName().Version?.ToString() ?? "unknown";
            var header = $"Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient {version}. Do not edit by hand.";

            var types = TypeGraph.Collect();
            Console.WriteLine($"Collected {types.Count} types: {string.Join(", ", types.Select(t => t.Name))}");

            var enumsWithoutZero = types
                .Where(t => t.IsEnum && TypeGraph.ZeroCase(t) == null)
                .Select(t => t.Name)
                .ToList();
            if (enumsWithoutZero.Count > 0)
                Console.WriteLine($"Warning: enums without a 0 member (ports default these to null and serialize 0): {string.Join(", ", enumsWithoutZero)}");

            var docs = XmlDocs.Load(assembly);

            new PhpEmitter(docs, header).Emit(types, phpOut);
            Console.WriteLine($"PHP DTOs written to {phpOut}");

            new JavaEmitter(docs, header).Emit(types, javaOut);
            Console.WriteLine($"Java DTOs written to {javaOut}");

            new FixtureWriter().Write(fixturesOut);
            Console.WriteLine($"Fixtures written to {fixturesOut}");
            return 0;
        }
    }
}
